import { StyleSheet } from "react-native";

export default StyleSheet.create({
  button: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    height: 70,
    backgroundColor: "#300",
    marginHorizontal: 50,
    borderWidth: 2,
    marginVertical: 8,
    borderRadius: 30,
  },
  deleteButton: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    height: 70,
    backgroundColor: "#E60012",
    marginHorizontal: 50,
    borderWidth: 2,
    marginVertical: 8,
    borderRadius: 30,
  },
  googleButton: {
    height: 70,
    alignSelf: "center",
  },
  appleButton: {
    height: 70,
    alignSelf: "center",
  },
  buttontext: {
    fontSize: 25,
    color: "#fff",
  },
  screen: {
    backgroundColor: "#3C9BE7",
    flex: 1,
  },
  columnScreen: {
    backgroundColor: "#3C9BE7",
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  userData: {
    flex: 1,
    color: "#fff",
    flexDirection: "column",
    justifyContent: "center",
  },

  text: {
    fontSize: 30,
  },
  normalText: {
    fontSize: 20,
    alignSelf: "center",
    marginBottom: 20,
  },
  userdataText: {
    fontSize: 20,
    color: "#fff",
    alignSelf: "center",
    marginBottom: 20,
  },
  userdataLabel: {
    fontSize: 20,
    color: "#fff",
    alignSelf: "center",
    marginBottom: 20,
  },
  buttonContainer: {
    height: 70,
  },
  settingsSpacer: {
    height: 230,
  },
  remindersSpacer: {
    height: 50,
  },
  inputContainer: {
    backgroundColor: "#eff",
    borderRadius: 30,
    marginVertical: 10,
    marginHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  input: {
    height: 60,
    width: 250,
    fontSize: 30,
    color: "#000",
  },
  clickableText: {
    fontSize: 30,
    textDecorationLine: "underline",
    justifyContent: "center",
    alignItems: "center",
  },
  clickableTextRed: {
    color: "red",
    fontSize: 30,
    textDecorationLine: "underline",
    justifyContent: "center",
    alignItems: "center",
  },
  dateinput: {
    height: 60,
    fontSize: 20,
    color: "#000",
  },
  confirmationInputContainer: {
    backgroundColor: "#eff",
    borderRadius: 30,
    marginVertical: 10,
    marginHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmationInput: {
    height: 60,
    width: 250,
    fontSize: 20,
    color: "#000",
  },
  occurrenceInputContainer: {
    backgroundColor: "#eff",
    borderRadius: 30,
    marginVertical: 5,
    marginHorizontal: 70,
    alignItems: "center",
    justifyContent: "center",
  },
  occurrenceInput: {
    height: 60,
    fontSize: 30,
    color: "#000",
  },
  picker: {
    height: 60,
    fontSize: 30,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerContainer: {
    height: 60,
    marginHorizontal: 20,
    backgroundColor: "#eff",
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 10,
    flexDirection: "row",
  },
  occurrencePicker: {
    width: 250,
    fontSize: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  occurrencePickerContainer: {
    height: 50,
    marginHorizontal: 70,
    backgroundColor: "#eff",
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 10,
  },
  occurrenceSpacer: {
    height: 20,
  },
  reminderListItem: {
    marginVertical: 10,
    marginHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eff",
    borderRadius: 10,
    flexDirection: "row",
  },
  reminderListItemTextView: {
    alignItems: "center",
    justifyContent: "center",
    flex: 4,
  },
  reminderListItemButtonView: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    borderRadius: 5,
    marginLeft: 5,
    marginVertical: 5,
  },
  reminderListItemButtonText: {
    fontSize: 50,
  },
  listItem: {
    marginVertical: 10,
    marginHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eff",
    borderRadius: 10,
  },
  listItemTitleText: {
    fontSize: 24,
  },
  listItemSubtext: {
    fontSize: 18,
  },
  contactsSpacer: {
    height: 120,
  },
  homeScreenText: {
    fontSize: 21,
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    textAlign: "center",
  },
  errorContainer: {
    flex: 1,
    flexDirection: "column",
    alignItems: "stretch",
    justifyContent: "center",
    alignContent: "center",
    paddingHorizontal: 12,
  },
  noReminderScreen: {
    backgroundColor: "#3C9BE7",
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    textAlign: "center",
  },
  rowBasedView: {
    flex: 1,
    flexDirection: "row",
  },
  timeRow: {
    marginVertical: 10,
    marginHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eff",
    borderRadius: 10,
    width: "80%",
  },
  removeTime: {
    alignItems: "center",
    justifyContent: "center",
  },
  removeTimeButton: {
    color: "red",
    fontSize: 30,
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  saveTimeButton: {
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    backgroundColor: "#300",
    borderRadius: 25,
    position: "absolute",
    bottom: 20,
    height: 50,
    width: "70%",
    left: 20,
  },
  addTimeButton: {
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.2)",
    alignItems: "center",
    justifyContent: "center",
    width: 50,
    height: 50,
    backgroundColor: "#300",
    borderRadius: 25,
    position: "absolute",
    bottom: 20,
    right: 20,
  },
  addText: { fontSize: 30, color: "#fff" },
  chevron: {
    fontSize: 30,
    position: "absolute",
    right: 25, // Keep some space between your left border and Image
  },
  inputIOS: {
    fontSize: 25,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderWidth: 0,
    color: "black",
    paddingRight: 30, // to ensure the text is never behind the icon
  },
  inputAndroid: {
    fontSize: 25,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 0,
    color: "black",
    paddingRight: 70, // to ensure the text is never behind the icon
  },
  smallDoneButton: {
    fontSize: 18,
    position: "absolute",
    right: -65,
    color: "blue",
  },
  homeSpacer: {
    height: 60,
  },
  spinnerTextStyle: {
    color: "#FFF",
  },
});
